apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s8u86948h-dotnet-basic
  janus-idp.io/tekton: s8u86948h-dotnet-basic
  backstage.io/kubernetes-id: s8u86948h-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s8u86948h-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
